// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

open BigIntCalculator

# 10 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | ABS
  | RBR
  | LBR
  | EQ
  | KW_PRINT
  | KW_LET
  | VNAME of (string)
  | BIN
  | POW
  | REM
  | DIV
  | MUL
  | SUB
  | SUM
  | NUM of (BigIntFunctions.bInt)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_ABS
    | TOKEN_RBR
    | TOKEN_LBR
    | TOKEN_EQ
    | TOKEN_KW_PRINT
    | TOKEN_KW_LET
    | TOKEN_VNAME
    | TOKEN_BIN
    | TOKEN_POW
    | TOKEN_REM
    | TOKEN_DIV
    | TOKEN_MUL
    | TOKEN_SUB
    | TOKEN_SUM
    | TOKEN_NUM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_stmt
    | NONTERM_expr
    | NONTERM_rexpr
    | NONTERM_baseAndPow
    | NONTERM_power
    | NONTERM_vname
    | NONTERM_eof

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | ABS  -> 1 
  | RBR  -> 2 
  | LBR  -> 3 
  | EQ  -> 4 
  | KW_PRINT  -> 5 
  | KW_LET  -> 6 
  | VNAME _ -> 7 
  | BIN  -> 8 
  | POW  -> 9 
  | REM  -> 10 
  | DIV  -> 11 
  | MUL  -> 12 
  | SUB  -> 13 
  | SUM  -> 14 
  | NUM _ -> 15 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_ABS 
  | 2 -> TOKEN_RBR 
  | 3 -> TOKEN_LBR 
  | 4 -> TOKEN_EQ 
  | 5 -> TOKEN_KW_PRINT 
  | 6 -> TOKEN_KW_LET 
  | 7 -> TOKEN_VNAME 
  | 8 -> TOKEN_BIN 
  | 9 -> TOKEN_POW 
  | 10 -> TOKEN_REM 
  | 11 -> TOKEN_DIV 
  | 12 -> TOKEN_MUL 
  | 13 -> TOKEN_SUB 
  | 14 -> TOKEN_SUM 
  | 15 -> TOKEN_NUM 
  | 18 -> TOKEN_end_of_input
  | 16 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_start 
    | 3 -> NONTERM_stmt 
    | 4 -> NONTERM_stmt 
    | 5 -> NONTERM_stmt 
    | 6 -> NONTERM_stmt 
    | 7 -> NONTERM_stmt 
    | 8 -> NONTERM_stmt 
    | 9 -> NONTERM_stmt 
    | 10 -> NONTERM_stmt 
    | 11 -> NONTERM_stmt 
    | 12 -> NONTERM_stmt 
    | 13 -> NONTERM_stmt 
    | 14 -> NONTERM_stmt 
    | 15 -> NONTERM_stmt 
    | 16 -> NONTERM_stmt 
    | 17 -> NONTERM_expr 
    | 18 -> NONTERM_expr 
    | 19 -> NONTERM_expr 
    | 20 -> NONTERM_rexpr 
    | 21 -> NONTERM_rexpr 
    | 22 -> NONTERM_rexpr 
    | 23 -> NONTERM_rexpr 
    | 24 -> NONTERM_baseAndPow 
    | 25 -> NONTERM_baseAndPow 
    | 26 -> NONTERM_power 
    | 27 -> NONTERM_power 
    | 28 -> NONTERM_power 
    | 29 -> NONTERM_power 
    | 30 -> NONTERM_power 
    | 31 -> NONTERM_vname 
    | 32 -> NONTERM_eof 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 18 
let _fsyacc_tagOfErrorTerminal = 16

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | ABS  -> "ABS" 
  | RBR  -> "RBR" 
  | LBR  -> "LBR" 
  | EQ  -> "EQ" 
  | KW_PRINT  -> "KW_PRINT" 
  | KW_LET  -> "KW_LET" 
  | VNAME _ -> "VNAME" 
  | BIN  -> "BIN" 
  | POW  -> "POW" 
  | REM  -> "REM" 
  | DIV  -> "DIV" 
  | MUL  -> "MUL" 
  | SUB  -> "SUB" 
  | SUM  -> "SUM" 
  | NUM _ -> "NUM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | ABS  -> (null : System.Object) 
  | RBR  -> (null : System.Object) 
  | LBR  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | KW_PRINT  -> (null : System.Object) 
  | KW_LET  -> (null : System.Object) 
  | VNAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | BIN  -> (null : System.Object) 
  | POW  -> (null : System.Object) 
  | REM  -> (null : System.Object) 
  | DIV  -> (null : System.Object) 
  | MUL  -> (null : System.Object) 
  | SUB  -> (null : System.Object) 
  | SUM  -> (null : System.Object) 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 2us; 65535us; 0us; 1us; 2us; 3us; 2us; 65535us; 0us; 2us; 2us; 2us; 4us; 65535us; 8us; 9us; 40us; 23us; 42us; 24us; 46us; 25us; 6us; 65535us; 8us; 22us; 26us; 27us; 28us; 29us; 40us; 22us; 42us; 22us; 46us; 22us; 9us; 65535us; 8us; 30us; 26us; 30us; 28us; 30us; 31us; 32us; 33us; 34us; 35us; 36us; 40us; 30us; 42us; 30us; 46us; 30us; 10us; 65535us; 8us; 37us; 26us; 37us; 28us; 37us; 31us; 37us; 33us; 37us; 35us; 37us; 38us; 39us; 40us; 37us; 42us; 37us; 46us; 37us; 14us; 65535us; 0us; 10us; 2us; 10us; 4us; 5us; 6us; 7us; 8us; 45us; 26us; 45us; 28us; 45us; 31us; 45us; 33us; 45us; 35us; 45us; 38us; 45us; 40us; 45us; 42us; 45us; 46us; 45us; 0us; 65535us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 4us; 7us; 12us; 19us; 29us; 40us; 55us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 2us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 4us; 3us; 4us; 18us; 19us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 13us; 1us; 14us; 1us; 15us; 1us; 16us; 4us; 17us; 21us; 22us; 23us; 3us; 18us; 19us; 26us; 3us; 18us; 19us; 27us; 3us; 18us; 19us; 30us; 1us; 18us; 4us; 18us; 21us; 22us; 23us; 1us; 19us; 4us; 19us; 21us; 22us; 23us; 2us; 20us; 25us; 1us; 21us; 2us; 21us; 25us; 1us; 22us; 2us; 22us; 25us; 1us; 23us; 2us; 23us; 25us; 1us; 24us; 1us; 25us; 1us; 25us; 1us; 26us; 1us; 26us; 1us; 27us; 1us; 27us; 1us; 28us; 1us; 29us; 1us; 30us; 1us; 31us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 9us; 11us; 13us; 15us; 17us; 19us; 23us; 25us; 27us; 29us; 31us; 33us; 35us; 37us; 39us; 41us; 43us; 45us; 47us; 52us; 56us; 60us; 64us; 66us; 71us; 73us; 78us; 81us; 83us; 86us; 88us; 91us; 93us; 96us; 98us; 100us; 102us; 104us; 106us; 108us; 110us; 112us; 114us; 116us; |]
let _fsyacc_action_rows = 48
let _fsyacc_actionTableElements = [|14us; 32768us; 1us; 14us; 2us; 13us; 3us; 12us; 5us; 4us; 6us; 6us; 7us; 47us; 8us; 21us; 9us; 20us; 10us; 19us; 11us; 17us; 12us; 16us; 13us; 18us; 14us; 15us; 15us; 11us; 0us; 49152us; 14us; 16385us; 1us; 14us; 2us; 13us; 3us; 12us; 5us; 4us; 6us; 6us; 7us; 47us; 8us; 21us; 9us; 20us; 10us; 19us; 11us; 17us; 12us; 16us; 13us; 18us; 14us; 15us; 15us; 11us; 0us; 16386us; 1us; 32768us; 7us; 47us; 0us; 16387us; 1us; 32768us; 7us; 47us; 1us; 32768us; 4us; 8us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 2us; 16388us; 13us; 28us; 14us; 26us; 0us; 16389us; 0us; 16390us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 0us; 16396us; 0us; 16397us; 0us; 16398us; 0us; 16399us; 0us; 16400us; 3us; 16401us; 10us; 35us; 11us; 33us; 12us; 31us; 3us; 32768us; 2us; 41us; 13us; 28us; 14us; 26us; 3us; 32768us; 1us; 43us; 13us; 28us; 14us; 26us; 2us; 16414us; 13us; 28us; 14us; 26us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 3us; 16402us; 10us; 35us; 11us; 33us; 12us; 31us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 3us; 16403us; 10us; 35us; 11us; 33us; 12us; 31us; 1us; 16404us; 9us; 38us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 1us; 16405us; 9us; 38us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 1us; 16406us; 9us; 38us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 1us; 16407us; 9us; 38us; 0us; 16408us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 0us; 16409us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 0us; 16410us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 0us; 16411us; 0us; 16412us; 0us; 16413us; 5us; 32768us; 1us; 42us; 3us; 40us; 7us; 47us; 8us; 46us; 15us; 44us; 0us; 16415us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 15us; 16us; 31us; 32us; 34us; 35us; 37us; 39us; 45us; 48us; 49us; 50us; 51us; 52us; 53us; 54us; 55us; 56us; 57us; 58us; 59us; 60us; 64us; 68us; 72us; 75us; 81us; 85us; 91us; 95us; 97us; 103us; 105us; 111us; 113us; 119us; 121us; 122us; 128us; 129us; 135us; 136us; 142us; 143us; 144us; 145us; 151us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 2us; 2us; 4us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 3us; 3us; 1us; 3us; 3us; 3us; 1us; 3us; 3us; 3us; 1us; 1us; 2us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 3us; 3us; 3us; 4us; 4us; 4us; 4us; 5us; 5us; 6us; 6us; 6us; 6us; 6us; 7us; 8us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16386us; 65535us; 16387us; 65535us; 65535us; 65535us; 65535us; 16389us; 16390us; 16391us; 16392us; 16393us; 16394us; 16395us; 16396us; 16397us; 16398us; 16399us; 16400us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16408us; 65535us; 16409us; 65535us; 16410us; 65535us; 16411us; 16412us; 16413us; 65535us; 16415us; |]
let _fsyacc_reductions ()  =    [| 
# 195 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?>  AST.Program  in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startstart));
# 204 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_stmt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "Parser.fsy"
                                  [_1]
                   )
# 29 "Parser.fsy"
                 :  AST.Program ));
# 215 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_stmt in
            let _2 = parseState.GetInput(2) :?>  AST.Program  in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "Parser.fsy"
                                        _1 :: _2
                   )
# 30 "Parser.fsy"
                 :  AST.Program ));
# 227 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_vname in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "Parser.fsy"
                                           AST.Print(_2)
                   )
# 32 "Parser.fsy"
                 : 'gentype_stmt));
# 238 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_vname in
            let _4 = parseState.GetInput(4) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "Parser.fsy"
                                                 AST.VDecl(_2,_4)
                   )
# 33 "Parser.fsy"
                 : 'gentype_stmt));
# 250 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_vname in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "Parser.fsy"
                                  failwith "parse error of variable name"
                   )
# 34 "Parser.fsy"
                 : 'gentype_stmt));
# 261 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> BigIntFunctions.bInt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "Parser.fsy"
                                failwith "parse error of num" 
                   )
# 35 "Parser.fsy"
                 : 'gentype_stmt));
# 272 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "Parser.fsy"
                                failwith "parse error: of left brackets"
                   )
# 36 "Parser.fsy"
                 : 'gentype_stmt));
# 282 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "Parser.fsy"
                                failwith "parse error of right brackets"
                   )
# 37 "Parser.fsy"
                 : 'gentype_stmt));
# 292 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "Parser.fsy"
                                failwith "parse error of abs"
                   )
# 38 "Parser.fsy"
                 : 'gentype_stmt));
# 302 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "Parser.fsy"
                                failwith "parse error of sum"
                   )
# 39 "Parser.fsy"
                 : 'gentype_stmt));
# 312 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "Parser.fsy"
                                failwith "parse error of mult"
                   )
# 40 "Parser.fsy"
                 : 'gentype_stmt));
# 322 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "Parser.fsy"
                                failwith "parse error of div"
                   )
# 41 "Parser.fsy"
                 : 'gentype_stmt));
# 332 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "Parser.fsy"
                                failwith "parse error of sub"
                   )
# 42 "Parser.fsy"
                 : 'gentype_stmt));
# 342 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "Parser.fsy"
                                failwith "parse error of rem"
                   )
# 43 "Parser.fsy"
                 : 'gentype_stmt));
# 352 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "Parser.fsy"
                                failwith "parse error of pow"
                   )
# 44 "Parser.fsy"
                 : 'gentype_stmt));
# 362 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "Parser.fsy"
                                failwith "parse error of bin"
                   )
# 45 "Parser.fsy"
                 : 'gentype_stmt));
# 372 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_rexpr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "Parser.fsy"
                                  _1
                   )
# 47 "Parser.fsy"
                 : 'gentype_expr));
# 383 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_rexpr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "Parser.fsy"
                                           AST.Sum(_1, _3)
                   )
# 48 "Parser.fsy"
                 : 'gentype_expr));
# 395 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_rexpr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "Parser.fsy"
                                           AST.Sub(_1, _3)
                   )
# 49 "Parser.fsy"
                 : 'gentype_expr));
# 407 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_baseAndPow in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "Parser.fsy"
                                        _1
                   )
# 51 "Parser.fsy"
                 : 'gentype_rexpr));
# 418 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_rexpr in
            let _3 = parseState.GetInput(3) :?> 'gentype_baseAndPow in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "Parser.fsy"
                                                 AST.Mul(_1, _3)
                   )
# 52 "Parser.fsy"
                 : 'gentype_rexpr));
# 430 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_rexpr in
            let _3 = parseState.GetInput(3) :?> 'gentype_baseAndPow in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "Parser.fsy"
                                                 AST.Div(_1, _3)
                   )
# 53 "Parser.fsy"
                 : 'gentype_rexpr));
# 442 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_rexpr in
            let _3 = parseState.GetInput(3) :?> 'gentype_baseAndPow in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "Parser.fsy"
                                                 AST.Rem(_1, _3)
                   )
# 54 "Parser.fsy"
                 : 'gentype_rexpr));
# 454 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_power in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "Parser.fsy"
                                        _1
                   )
# 56 "Parser.fsy"
                 : 'gentype_baseAndPow));
# 465 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_baseAndPow in
            let _3 = parseState.GetInput(3) :?> 'gentype_power in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "Parser.fsy"
                                                 AST.Pow(_1, _3)
                   )
# 57 "Parser.fsy"
                 : 'gentype_baseAndPow));
# 477 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 59 "Parser.fsy"
                                          _2
                   )
# 59 "Parser.fsy"
                 : 'gentype_power));
# 488 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 60 "Parser.fsy"
                                         AST.Abs _2
                   )
# 60 "Parser.fsy"
                 : 'gentype_power));
# 499 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> BigIntFunctions.bInt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "Parser.fsy"
                                AST.Num(_1)
                   )
# 61 "Parser.fsy"
                 : 'gentype_power));
# 510 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_vname in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "Parser.fsy"
                                  AST.NVar(_1)
                   )
# 62 "Parser.fsy"
                 : 'gentype_power));
# 521 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "Parser.fsy"
                                     AST.Bin _2
                   )
# 63 "Parser.fsy"
                 : 'gentype_power));
# 532 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "Parser.fsy"
                                   AST.Var(_1)
                   )
# 65 "Parser.fsy"
                 : 'gentype_vname));
# 543 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "Parser.fsy"
                               1
                   )
# 67 "Parser.fsy"
                 : 'gentype_eof));
|]
# 554 "Parser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 19;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  AST.Program  =
    engine lexer lexbuf 0 :?> _
